ConnectionStrings:
  DefaultConnection: "Server=127.0.0.1;Port=5432;Database=ss14-auth-test"

Logging:
  LogLevel:
    Default: "Information"
    Microsoft: "Warning"
    Microsoft.Hosting.Lifetime: "Information"
