Serilog:
  Using: [ "Serilog.Sinks.Console", "Serilog.Sinks.Loki" ]
  MinimumLevel:
    Default: Verbose
    Override:
      SS14: Debug
      Microsoft: "Verbose"
      Microsoft.Hosting.Lifetime: "Verbose"
      Microsoft.AspNetCore: Verbose

  WriteTo:
    - Name: Console
      Args:
        OutputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}"

  Enrich: [ "FromLogContext" ]

  #Loki:
  #  Address: "http://localhost:3100"
  #  Name: "Test"

ForwardProxies:
  - 127.0.0.1

AllowedHosts: "*"