Logging:
  LogLevel:
    Default: "Information"
    Microsoft: "Warning"
    Microsoft.Hosting.Lifetime: "Information"


AllowedHosts: "*"

Servers:
  - Name: Foo
    Address: Bar

  - Name: Syndicate Mothership
    Address: Honk
