ConnectionStrings:
  DefaultConnection: "Server=127.0.0.1;Port=5432;Database=ss14-auth-test"

urls: "http://localhost:5000"

Logging:
  LogLevel:
    Default: "Information"
    SS14: "Debug"
    Microsoft: "Warning"
    Microsoft.Hosting.Lifetime: "Information"
